name: First Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        run: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.9'
      - run: python script.py
