name: Ignore path workflow
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - 'dev*'
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev*'
      - 'test*'
    paths-ignore:
      - './github/workflows/*'

jobs:
  build:
    name: Some example job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.9'
      - run: python script.py
      - uses: actions/upload-artifact@v4
        with:
          name: myartifact
          path: artifact-folder
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: myartifact
        run: ls

